Issue 16 17 18
wwllaad/station-passport pull request #20
Opened 2018-02-14 10:03 UTC by wwllaad

2018-02-15 09:09 UTC, lantushenkoao requested changes

2018-02-15 09:09 UTC, lantushenkoao commented on src/main/java/com/sevgmo/stationpassport/StationPassportApplication.java
> +
Remove redundant blank lines

2018-02-15 09:09 UTC, lantushenkoao commented on src/main/java/com/sevgmo/stationpassport/model/Section.java
> +    public Section getSection() {
rename to getParent()

2018-02-15 09:09 UTC, lantushenkoao commented on src/main/java/com/sevgmo/stationpassport/serialize/CustomFieldDTO.java
> +    private Section section;
DTO classes should not have domain objects as fields

2018-02-15 09:09 UTC, lantushenkoao commented on src/main/java/com/sevgmo/stationpassport/service/StationService.java
> +    public CustomField getCustomFieldById(int id){
Do not serialize domain objects directly. Use DTOs

2018-02-15 09:09 UTC, lantushenkoao commented on src/main/java/com/sevgmo/stationpassport/service/StationService.java
>          for(CustomFieldValueDTO customFieldValueDTO : customFieldValueDTOList){
Consider using array utility methods, like
customFieldValueDTOList.forEach

2018-02-15 09:09 UTC, lantushenkoao commented on src/main/java/com/sevgmo/stationpassport/service/StationService.java
>          for(CustomFieldDTO customFieldDTO : customFieldDTOList){
Consider using Java8 streams here, like customFieldDTOList.stream()....

2018-02-16 08:22 UTC, wwllaad commented
Requested changes were made.

2018-02-17 14:58 UTC, merged